# vi:filetype=python:expandtab:tabstop=2:shiftwidth=2
import os

Import('env')

lenv = env.Clone()

sources = Split("""
                hkl-test.h
                hkl-test.c
                hkl-test-vector.c
                hkl-test-matrix.c
                hkl-test-quaternion.c
                hkl-test-interval.c
                hkl-test-source.c
                hkl-test-axis.c
                hkl-test-holder.c
                hkl-test-geometry.c
                hkl-test-detector.c
                hkl-test-parameter.c
                hkl-test-lattice.c
                hkl-test-sample.c
                main.c
                """)

"""
                hkl-test-list.c
                hkl-test-pseudoaxis.c
		"""
includes = ['../src']

libpath = ['../src']

libs = ['hkl', 'gsl', 'gslcblas']
if os.name == 'posix':
  libs += ['m', 'dl']

lenv.AppendUnique(CPPPATH = includes)
lenv.AppendUnique(LIBS = libs)
lenv.AppendUnique(LIBPATH = libpath)

lenv.MergeFlags(['!pkg-config glib-2.0 --cflags --libs'])
lenv.MergeFlags(['!pkg-config gobject-2.0 --cflags --libs'])
test = lenv.Program(target = 'test', source = sources)
lenv.Test("test.passed", test)
Default(lenv.Alias("check", "test.passed"))
