--- !ditz.rubyforge.org,2008-03-06/project 
name: hkl
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: hkl
- !ditz.rubyforge.org,2008-03-06/component 
  name: hkl3d
- !ditz.rubyforge.org,2008-03-06/component 
  name: ghkl
releases: []

