# vi:filetype=python:expandtab:tabstop=2:shiftwidth=2
Import('env')

lenv = env.Clone()

sources_vala = Split("""
         hkl-constants.vala
         hkl-vector.vala
         hkl-interval.vala
         hkl-source.vala
         hkl-axis.vala
         hkl-list.vala
         hkl-holder.vala
         hkl-geometry.vala
         """)

sources = Split("""
                usage.c
                """)
"""

                hkl-detector.c
                hkl-parameter.c
                hkl-lattice.c
                hkl-sample.c
                hkl-pseudoaxis.c
                hkl-pseudoaxis-auto.c
                """

includes = ['.']

lenv.AppendUnique(CPPPATH = includes)
lenv.MergeFlags(['!pkg-config glib-2.0 --cflags --libs'])

vala = lenv.Vala(sources_vala)

libhkl = lenv.Library(target = 'hkl', source = [vala, sources])
Default(libhkl)
