# vi:filetype=python:expandtab:tabstop=2:shiftwidth=2
Import('env')

lenv = env.Clone()

sources_vala = Split("""
         hkl-constants.vala
         hkl-vector.vala
         hkl-interval.vala
         hkl-source.vala
         hkl-axis.vala
         hkl-list.vala
         hkl-holder.vala
         hkl-geometry.vala
         hkl-detector.vala
         hkl-parameter.vala
         hkl-lattice.vala
         hkl-sample.vala
         hkl-pseudoaxis.vala
         hkl-pseudoaxis-auto.vala
         hkl-pseudoaxis-auto-E4CV.vala
         hkl-pseudoaxis-auto-K4CV.vala
         """)

sources = Split("""
                usage.c
                """)

includes = ['.']

lenv.AppendUnique(CPPPATH = includes)
lenv.MergeFlags(['!pkg-config glib-2.0 --cflags --libs'])

vala = lenv.Vala(sources_vala)

libhkl = lenv.Library(target = 'hkl', source = [vala, sources])
Default(libhkl)
