#! /usr/bin/env python
# encoding: utf-8

obj = bld.new_task_gen('cc', 'shlib')
obj.find_sources_in_dirs('.')
obj.cflags = '-g -Wall -Wno-uninitialized -Wcast-align -Wformat-security -Werror'
obj.target = 'hkl'
obj.packages = 'gsl'
obj.uselib = 'GSL GLIB'
obj.includes = '../include'
obj.vnum = bld.env['HKL_VERSION']
