#! /usr/bin/env python
# encoding: utf-8

obj = bld.new_task_gen(
		features=['cc', 'cshlib'],
		target = 'hkl',
		cflags = ['--std=c99', '-g'],
		packages = ['gsl'],
		uselib = ['GSL', 'GOBJECT'],
		includes = ['.'],
		vnum = bld.env['HKL_VERSION'])
obj.find_sources_in_dirs('.')
